# Generated by Django 3.2 on 2024-02-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='level',
            field=models.IntegerField(default=999),
            preserve_default=False,
        ),
    ]
